# Generated by Django 3.2.15 on 2022-08-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='note',
            name='image_url',
            field=models.URLField(verbose_name='Link to Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(verbose_name='Link to Profile Image'),
        ),
    ]
