# Generated by Django 3.2.15 on 2022-08-24 17:57

import Expenses_tracker.main.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_expense_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[Expenses_tracker.main.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
