# Generated by Django 3.2.15 on 2022-08-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220824_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_image',
            new_name='image',
        ),
    ]
